// Code generated by Slice Machine. DO NOT EDIT.

import ArchiveOld from './ArchiveOld';
import BlogPostsList from './BlogPostsList';
import ChildsList from './ChildsList';
import CtaHorizontal from './CtaHorizontal';
import Expertises from './Expertises';
import Faq from './Faq';
import HeroHome from './HeroHome';
import HeroStandard from './HeroStandard';
import ImageAlone from './ImageAlone';
import ImageFeaturedLeft from './ImageFeaturedLeft';
import ImageFeaturedRight from './ImageFeaturedRight';
import MyServices from './MyServices';
import PartnersBox from './PartnersBox';
import PartnersLine from './PartnersLine';
import PartnersSeo from './PartnersSeo';
import PartnersSliderSeo from './PartnersSliderSeo';
import Testimonials from './Testimonials';
import TextBoxLight from './TextBoxLight';
import TextContent from './TextContent';
import VideoPlayer from './VideoPlayer';

export {
	ArchiveOld,
	BlogPostsList,
	ChildsList,
	CtaHorizontal,
	Expertises,
	Faq,
	HeroHome,
	HeroStandard,
	ImageAlone,
	ImageFeaturedLeft,
	ImageFeaturedRight,
	MyServices,
	PartnersBox,
	PartnersLine,
	PartnersSeo,
	PartnersSliderSeo,
	Testimonials,
	TextBoxLight,
	TextContent,
	VideoPlayer,
};

export const components = {
	partners_slider_dev: ArchiveOld,
	blog_posts_list: BlogPostsList,
	internal_childs: ChildsList,
	cta_horizontal: CtaHorizontal,
	expertises: Expertises,
	faq: Faq,
	hero_home: HeroHome,
	hero_standard: HeroStandard,
	image_alone: ImageAlone,
	image_featured_left: ImageFeaturedLeft,
	image_featured_right: ImageFeaturedRight,
	my_services: MyServices,
	partners_line: PartnersBox,
	partners_dev: PartnersLine,
	partners_seo: PartnersSeo,
	partners_slider_seo: PartnersSliderSeo,
	testimonials: Testimonials,
	text_box_light: TextBoxLight,
	text_content: TextContent,
	video_player: VideoPlayer,
};
