// Code generated by Slice Machine. DO NOT EDIT.

import Faq from './Faq';
import HeroHome from './HeroHome';
import ImageFeatured from './ImageFeatured';

export {
	Faq,
	HeroHome,
	ImageFeatured,
};

export const components = {
	faq: Faq,
	hero_home: HeroHome,
	image_featured: ImageFeatured,
};
