// Code generated by Slice Machine. DO NOT EDIT.

import BlogPostsList from './BlogPostsList';
import CtaHorizontal from './CtaHorizontal';
import Faq from './Faq';
import HeroHome from './HeroHome';
import HeroStandard from './HeroStandard';
import ImageAlone from './ImageAlone';
import ImageFeaturedLeft from './ImageFeaturedLeft';
import ImageFeaturedRight from './ImageFeaturedRight';
import MyServices from './MyServices';
import PartnersDev from './PartnersDev';
import PartnersLine from './PartnersLine';
import PartnersSeo from './PartnersSeo';
import PartnersSliderDev from './PartnersSliderDev';
import PartnersSliderSeo from './PartnersSliderSeo';
import Testimonials from './Testimonials';
import TextBoxLight from './TextBoxLight';
import TextContent from './TextContent';
import VideoPlayer from './VideoPlayer';

export {
	BlogPostsList,
	CtaHorizontal,
	Faq,
	HeroHome,
	HeroStandard,
	ImageAlone,
	ImageFeaturedLeft,
	ImageFeaturedRight,
	MyServices,
	PartnersDev,
	PartnersLine,
	PartnersSeo,
	PartnersSliderDev,
	PartnersSliderSeo,
	Testimonials,
	TextBoxLight,
	TextContent,
	VideoPlayer,
};

export const components = {
	blog_posts_list: BlogPostsList,
	cta_horizontal: CtaHorizontal,
	faq: Faq,
	hero_home: HeroHome,
	hero_standard: HeroStandard,
	image_alone: ImageAlone,
	image_featured_left: ImageFeaturedLeft,
	image_featured_right: ImageFeaturedRight,
	my_services: MyServices,
	partners_dev: PartnersDev,
	partners_line: PartnersLine,
	partners_seo: PartnersSeo,
	partners_slider_dev: PartnersSliderDev,
	partners_slider_seo: PartnersSliderSeo,
	testimonials: Testimonials,
	text_box_light: TextBoxLight,
	text_content: TextContent,
	video_player: VideoPlayer,
};
