import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import HeroHome from "../components/ui/Homepage/HeroHome";
import PartnersBox from "../components/ui/Homepage/PartnersBox";
import FeaturedAbout from "../components/ui/Homepage/FeaturedAbout";
import MyServices from "../components/ui/Homepage/MyServices";
import { createClient } from "../prismicio";
import { components } from "../slices";
import { SliceZone } from "@prismicio/react";

export default function Homepage({ page, navigation, settings }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroHome />
        <PartnersBox />
        <FeaturedAbout />
        <MyServices />
        <SliceZone slices={page.data.slices} components={components} />
      </main>
    </div>
  );
}

export async function getStaticProps({ previewData }) {
  const client = createClient({ previewData });

  const page = await client.getSingle("homepage");

  return {
    props: {
      page,
    },
  };
}
