import Head from "next/head";

import { createClient } from "../prismicio";
import { components } from "../slices";
import { SliceZone } from "@prismicio/react";

export default function Homepage({ page, navigation, settings }) {
  return (
    <div>
      <Head>
        <title>Marving Moreton</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <SliceZone slices={page.data.slices} components={components} />
        {/* <CTAHorizontal /> */}
      </main>
    </div>
  );
}

export async function getStaticProps({ previewData }) {
  const client = createClient({ previewData });

  const page = await client.getSingle("homepage");

  return {
    props: {
      page,
    },
  };
}
