import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import HeroHome from "../components/ui/HeroHome";
import PartnersBox from "../components/ui/PartnersBox";
import FeaturedAbout from "../components/ui/FeaturedAbout";
import MyServices from "../components/ui/MyServices";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroHome />
        <PartnersBox />
        <FeaturedAbout />
        <MyServices />
      </main>
    </div>
  );
}
